language: c
os:
  - linux
  - osx
compiler:
  - clang
  - gcc
sudo: false
addons:
  apt:
    packages:
      - check
      - libruli4-dev
#      - libc-ares-dev
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install check c-ares gnutls ; fi
install: autoreconf --install
script: ./configure && make && make check
